### ISSUE TITLE
Create Example DAG

### ISSUE THREAD

**Issue by pgzmnk** [sutrolabs/airflow-provider-census#2]
Add an example DAG in `example_dags/`. This will appear in the registry.

Good example DAGs are those that show a contextual use case and approach users to a plug-and-play experience.

I'd recommend an `Operator -> Sensor` workflow.

**Comment by thomasdziedzic-census** [comment]
Does the `example_dags` have to be under the `airflow_provider_census` directory like with the [Fivetran provider](https://github.com/fivetran/airflow-provider-fivetran/tree/main/fivetran_provider/example_dags)?

**Comment by pgzmnk** [comment]
Correct. Same structure. 

This is so relevant metadata can easily be picked up.

**Comment by pgzmnk** [comment]
Hi @thomasdziedzic-census .

Could you please share an example of the Airflow connection structure required by `census_conn_id`? That way I can generate one with my Census account and validate the DAG runs. We can also add a sample connection structure to the README.md

**Comment by thomasdziedzic-census** [comment]
I have instructions on how to setup a new connection at https://github.com/sutrolabs/airflow-provider-census#configuration let me know if you need anything else!
