### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by pgzmnk** [sutrolabs/airflow-provider-census#3]
Unit tests should assert base functionality individually for the operator, hook, and sensor.

The [sample package](https://github.com/astronomer/airflow-provider-sample/blob/main/tests/hooks/test_sample_hook.py) shows the recommended approach.

I will verify that the unit tests execute successfully and capture an adequate scope.

**Comment by thomasdziedzic-census** [comment]
I do have unit tests under https://github.com/sutrolabs/airflow-provider-census/tree/master/tests so can you be more specific on what you would like to see?

I went through the tests and I had assertions for the hook and sensor, but I didn't see one for the operator so I will add one there.

**Comment by thomasdziedzic-census** [comment]
Added an assertion for the operator.
